# Generated by Django 5.0.6 on 2024-07-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_add_review_id_to_workspacephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacephoto',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='homepage.rating'),
            preserve_default=False,
        ),
    ]
