# Generated by Django 5.0.6 on 2024-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_workspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
