# Generated by Django 5.0.6 on 2024-06-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_category_photo_usertype_user_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
