# Generated by Django 5.0.6 on 2024-07-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_users_type_alter_report_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspacephoto',
            table='WorkspacePhoto',
        ),
    ]
