# Generated by Django 5.0.6 on 2024-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_workspacephoto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
