# Generated by Django 5.0.6 on 2024-07-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_workspace_latitude_workspace_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
