# Generated by Django 5.0.6 on 2024-07-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_workspace_email_workspace_phone_workspace_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.workspace'),
            preserve_default=False,
        ),
    ]
