# Generated by Django 5.0.6 on 2024-07-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_reviewvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewvote',
            old_name='vote_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='homepage.rating'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10),
        ),
    ]
